services:
  # wine-api:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./src:/app/src
  
  mimir:
    image: grafana/mimir:2.12.0
    container_name: mimir
    restart: unless-stopped
    command: --config.file=/etc/mimir.yaml
    ports:
      - 9090:9090
    volumes:
      - ./services/mimir/mimir.yaml:/etc/mimir.yaml
      - ./services/mimir/alertmanager.yaml:/etc/alertmanager-fallback-config.yaml
 
  loki:
    image: grafana/loki:3.1.0
    container_name: loki
    command: -config.file=/etc/loki/loki.yaml
    ports:
      - 3100:3100
    volumes:
      - ./services/loki/loki.yaml:/etc/loki/loki.yaml
      
  tempo:
    image: grafana/tempo:2.5.0
    container_name: tempo
    ports: 
      - 3200:3200
      - 4300:4317  # otlp grpc
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./services/tempo/tempo.yaml:/etc/tempo.yaml

  grafana:
    image: grafana/grafana:11.0.1
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - ./services/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./services/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./services/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki
      - tempo
      - mimir

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.120.0
    container_name: otelcol
    ports:
      - 4317:4317  # otlp grpc
      - 4318:4318  # otlp http
    command: --config=/etc/otelcol/config.yaml
    depends_on:
      - loki
      - tempo
      - mimir
      - grafana
    volumes:
      - ./services/otelcol/config.yaml:/etc/otelcol/config.yaml

  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"

    
  