{
 "title": "Application Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (http_server_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request/Second (RPS)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_total{job=\"wine_classifier\"}) / $__range_s\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Inference speed (Second)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(model_inference_cpu_time_seconds_bucket[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Request per endpoint",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (http_server_requests_total{job=\"wine_classifier\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# request per Method",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (http_server_requests_total{job=\"wine_classifier\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Error Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_server_errors_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Log & Trace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Application Log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{service_name=\"wine_classifier\"} |= ``"
    }
   ]
  },
  {
   "title": "Tracing",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "filters": [
      { "id": "34aed0a9", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "wine_classifier" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}